<?xml version="1.0"?>
<package format="2">
    <name>turtlebot3_ccpp</name>
    <version>0.1.0</version>
    <description>TurtleBot3 Flask 地圖即時監控</description>
    <maintainer email="hulk71777@gmail.com">MXHHulk</maintainer>
    <license>MIT</license>

    <buildtool_depend>catkin</buildtool_depend>

    <exec_depend>rospy</exec_depend>
    <exec_depend>nav_msgs</exec_depend>

    <!--
        pip3 install flask Pillow
        numpy 已隨 ROS 安裝
    -->
</package>
